### ISSUE TITLE
功能建议：提供镜像源延迟或网络连通性测试的功能

### ISSUE THREAD

**Issue by Steve-xmh** [wtklbm/crm#1]
这样的话可以帮助开发者根据自己的网络环境选择最合适的镜像源 😃

**Comment by wtklbm** [comment]
很好的功能建议

**Comment by wtklbm** [comment]
Hi，`crm` 更新了，并增加了 `test` 和 `best` 两个命令，`test` 用于显示各个镜像的网络延迟，而 `best` 则是测试网络延迟并应用最优的镜像源，欢迎再次反馈。
