### ISSUE TITLE
cargo install crm error

### ISSUE THREAD

**Issue by liuyunli** [wtklbm/crm#10]
error: there is no argument named `APP_VERSION`
   --> /home/x/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/crm-0.1.9/src/args.rs:105:30
    |
105 |             println!("  crm v{APP_VERSION}");
    |                              ^^^^^^^^^^^^^

error: there is no argument named `newest`
   --> /home/x/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/crm-0.1.9/src/args.rs:113:52
    |
113 |                         return println!("  检测到新版本: {newest}，请切换到官方镜像源以执行更新");
    |                                                          ^^^^^^^^

error: could not compile `crm` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `crm v0.1.9`, intermediate artifacts can be found at `/tmp/cargo-installI41pnE`

Caused by:
  build failed

**Comment by wtklbm** [comment]
更新 Rust 到新版试试

**Comment by liuyunli** [comment]
fixed with  `rustup update` thanks
