### ISSUE TITLE
可以添加 Rust 中国社区基础设施维护的镜像服务

### ISSUE THREAD

**Issue by NoahCell** [wtklbm/crm#12]
官网地址：https://infra.rust-lang.pub/

**Comment by NoahCell** [comment]
我已经提了一个 PR：https://github.com/wtklbm/crm/pull/13

**Comment by wtklbm** [comment]
感谢您的 PR，我发现 <https://infra.rust-lang.pub> 在我这里是打不开的 (超时而无法响应)，不知道是什么原因。PR 已合并了，因为官网打不开，所以镜像是不可用的
