### ISSUE TITLE
检测 config.toml 

### ISSUE THREAD

**Issue by kenchou** [wtklbm/crm#16]
当前只检测 `.cargo/config`（不带扩展名）。根据文档，可以使用 `config.toml`（推荐使用）
- https://doc.rust-lang.org/cargo/reference/config.html
- https://course.rs/cargo/reference/configuration.html

重现步骤：
- 存在 `~/.cargo/config.toml`
- 执行 `crm best sparse-download`

实际结果：
crm 新建了一个配置文件 `~/.cargo/config` （不带 .toml 扩展名）

然后 cargo 出现警告：
```
warning: Both `/home/xxx/.cargo/config` and `/home/xxx/.cargo/config.toml` exist. Using `/home/xxx/.cargo/config`
```

期望结果：
直接修改 `~/.cargo/config.toml`

注：根据文档描述，如果同时存在 `config` 和 `config.toml` 将使用 `config` 

期望 crm 的逻辑是先查找是否存在 `config` 文件，如果不存在再查找 `config.toml`

**Comment by wtklbm** [comment]
版本已更新到 `0.2.1`，可通过 `cargo install crm` 并使用 cargo 默认源进行安装
