### ISSUE TITLE
希望x86平台支持除了使用cargo外的下载工具

### ISSUE THREAD

**Issue by hijackthe2** [wtklbm/crm#18]
crm是个很好的工具。安装crm的目的是改变cargo源，下载rust依赖更快一些。但是，crm又是通过cargo来安装，导致安装crm很慢。如果可以通过别的简便方式来安装是更好的。

**Comment by wtklbm** [comment]
安装是一个麻烦事，如果想快速安装，则可以把预编译的二进制文件发布到操作系统的包管理器中，例如在 windows 上为 winget，scoop 等，mac 和 linux 为 brew 等。因为我不想去维护那些包，所以并没有将其上传到包管理器中。

另外，可以直接从这里下载预编译的二进制版本：https://github.com/wtklbm/crm/releases，将其下载后，保存到任意目录，然后将该目录放到操作系统的 PATH 环境变量中，您可以更加自由的管理该软件，半年甚至一年不更新也可以正常使用，可以用 `crm check-update` 来查询新版本，并进行更新。若要将 crm 批量安装到多台操作系统的话，这样会更加方便快捷。

如果您想到了更好的安装方式，也欢迎一起交流、PR

**Comment by hijackthe2** [comment]
感谢回复！有已经编译好的二进制就太好啦，这目前已经能解决我的问题了。我只注意到了readme中的教程，忽略了其他地方。我相信有人也会像我这样“懒惰”的，希望可以在readme中说明一下。

**Comment by wtklbm** [comment]
我更新了 README.md 文件，如果有任何问题，欢迎反馈
