### ISSUE TITLE
打扰一下，询问一下关于挺更库的情况。

### ISSUE THREAD

**Issue by Jiuyong** [wtklbm/crm#19]
不好意思，因为 rust-library-i18n 你停更后，issues 功能也没有了。所以只好到这里借宝地请教一下：
那个库的中文版本的内容库是在哪里的？比如，如果我想继续更新新版内容（比如，将新的 rust 文档翻译加入到中文版中，我该如何弄）
因为原来的库里面只有处理好的两个压缩包，没有中文版的版本管理库，可能是我愚昧蠢笨，我反复研究了好就都没知道，如果自己想接手这个库继续维护该如何弄，所以冒昧请教。
百忙中叨扰，实属抱歉。

**Comment by wtklbm** [comment]
并没有所谓的中文版的内容库，该翻译是经过一些特殊手段和大量的时间手动维护的，只有我才能把这个项目维护起来，其他人没有办法参与。
