### ISSUE TITLE
作为命令行程序，建议使用 clap 依赖

### ISSUE THREAD

**Issue by HairlessVillager** [wtklbm/crm#21]
首先感谢您对这个工具的贡献！我在这里提一个小的建议。

从我自己的角度出发，作为一个用 Rust 编写的命令行程序，和其他主流的命令行程序的使用风格保持一致是很重要的（最小惊讶原则）。我猜测 crm 应该是自行实现了一套命令行解析的逻辑，所以在使用的时候和其他的命令行工具（例如 cargo, rustc 等）有一定差异。

以下分别是这三个命令的输出结果截图：`cargo --help`, `rustc --help`, `crm --help`

![image](https://github.com/user-attachments/assets/482476c8-70e0-4794-96d1-05c4cd3ab184)

![image](https://github.com/user-attachments/assets/1cf0517c-0242-4113-97ae-ea2bee261ccb)

![image](https://github.com/user-attachments/assets/c18eafc7-d41e-4afb-8afe-be0971c96156)

所以我希望能用 clap 重构这个程序的命令行参数解析的相关代码，这样既减少了用户在使用时的惊讶，又能避免重复造轮子。clap 的 crate.io 链接：https://crates.io/crates/clap

**Comment by wtklbm** [comment]
嗨，对您的建议表示理解。在当初设计该程序时就是尽量少用一个库就少用一个库，在 README 中也有简短说明，考虑到这一点，没有添加通用命令行参数解析库。这个程序已经很久没有更新，如果改变命令解析方法，因兼容问题，会给所有已经使用长时间这个程序的人带来负担，但这不妨碍程序更新至 1.0，如果有人愿意为其添加命令行解析库并提 PR，我会非常愿意合并它。

**Comment by wtklbm** [comment]
如果使用该程序很久了，大家习惯上已经接受这种命令行风格了，添加新的命令行解析库并不是急迫需求。

**Comment by HairlessVillager** [comment]
好的，那我先关掉这个 issue，如果后人需要可以重新打开。
