### ISSUE TITLE
更新指定镜像源index

### ISSUE THREAD

**Issue by songzhi** [wtklbm/crm#3]
VSCode的crates插件好像默认只使用crates.io的local index，主要使用其他镜像源时它的提示信息就会不准。需要切回默认设置更新。基本就是
```shell
$ crm default
$ cargo update
$ crm use <name>
```
所以希望crm有一个更新指定（主要是默认）镜像源的功能。如`crm update <name>`，或者`crm default update`。

**Comment by wtklbm** [comment]
等过段时间有空了就实现哈☺

**Comment by wtklbm** [comment]
您好，我更新了 `crm` 主程序，并添加了 `crm update` 和 `crm install` 命令，这些命令其实只是一个简单的包装，它们在执行时都会自动切换为官方镜像，避免了手动切换的麻烦。因为 `crm` 还没有发布新版本，所以您可以将代码克隆到本地，并执行 `cargo build`，看看功能是不是您所需要的。

现在，您只需要在您的项目中，执行 `crm update` 命令即可，它会默认切换到到官方镜像源，当命令执行完之后会自动切换到之前的镜像源。

如果有任何的问题，欢迎再次与我联系，期待您的再次反馈。
