### ISSUE TITLE
error: could not compile `autocfg`

### ISSUE THREAD

**Issue by crackfan** [wtklbm/crm#4]
C:\Users\Administrator>cargo install crm
    Updating `https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index` index
  Installing crm v0.1.7
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling winapi v0.3.9
   Compiling autocfg v1.0.1
   Compiling cc v1.0.69
error: failed to build archive: Function not implemented

error: aborting due to previous error

error: could not compile `autocfg`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to build archive: Function not implemented

error: aborting due to previous error

error: failed to compile `crm v0.1.7`, intermediate artifacts can be found at `Z:\TEMP\cargo-installEs3b8x`

Caused by:
  build failed

**Comment by wtklbm** [comment]
先切换到官方镜像源，然后在进行安装试试。

```bash
crm default
cargo install crm --verbose
```

如果继续报错，把错误贴出来哈

**Comment by crackfan** [comment]
error: failed to build archive: Function not implemented

error: aborting due to previous error

error: could not compile `autocfg`

Caused by:
  process didn't exit successfully: `rustc --crate-name autocfg E:\Cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\autocfg-1.0.1\src\lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off -C metadata=b51e4be1685d4f2e -C extra-filename=-b51e4be1685d4f2e --out-dir Z:\TEMP\cargo-installp666gY\release\deps -L dependency=Z:\TEMP\cargo-installp666gY\release\deps --cap-lints allow` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: failed to build archive: Function not implemented

error: aborting due to previous error

error: failed to compile `crm v0.1.7`, intermediate artifacts can be found at `Z:\TEMP\cargo-installp666gY`

Caused by:
  build failed

**Comment by crackfan** [comment]
C:\Users\Administrator>cargo install crm --verbose
    Updating crates.io index
  Downloaded crm v0.1.7


error: failed to build archive: Function not implemented

error: aborting due to previous error

error: could not compile `autocfg`

Caused by:
  process didn't exit successfully: `rustc --crate-name autocfg E:\Cargo\registry\src\github.com-1ecc6299db9ec823\autocfg-1.0.1\src\lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debug-assertions=off -C metadata=b51e4be1685d4f2e -C extra-filename=-b51e4be1685d4f2e --out-dir Z:\TEMP\cargo-installDDcMZw\release\deps -L dependency=Z:\TEMP\cargo-installDDcMZw\release\deps --cap-lints allow` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: failed to build archive: Function not implemented

error: aborting due to previous error

error: failed to compile `crm v0.1.7`, intermediate artifacts can be found at `Z:\TEMP\cargo-installDDcMZw`

Caused by:
  build failed

**Comment by wtklbm** [comment]
我找了一台拥有 gnu 环境的笔记本，特意测试了一下。发现是可以编译通过的。


![2021-08-07_15 18 38](https://user-images.githubusercontent.com/26459487/128592191-5fbbf675-18eb-498d-bcb3-553207d216cb.png)



如果您始终无法编译通过，建议您先用老版本或者用下面这个编译好的二进制文件：

链接: https://pan.baidu.com/s/1vNX5kluBJcY-XX_KCOdWbA 提取码: 4uh4

**Comment by wtklbm** [comment]
我这边目前还没有发现编译不了的情况，gnu 和 msvc 两个工具链在我这里都编译通过了

**Comment by crackfan** [comment]
gnu 版本、环境变量分别是什么~我的始终无法编译成功 无论gnu、msvc

**Comment by crackfan** [comment]
> 我这边目前还没有发现编译不了的情况，gnu 和 msvc 两个工具链在我这里都编译通过了

麻烦您贴下 您的msvc gnu环境变量配置 以及版本号 谢谢

我这里msvc、gnu 都不顺利！安装倒没什么

**Comment by wtklbm** [comment]
我没有配什么环境变量，我这里的 Rust 环境都是新安装的，所以你就安装最新的版本就行了，不过我还是建议你使用 msvc 版本，因为 gnu 版本编译出来的二进制文件是 4 MB，而 msvc 版本编译出来就 1.5 MB。

gnu 版本要使用 msys2，安装后别忘记安装 cmake gcc base-devel mingw-w64-x86_64-toolchain 什么的，不安不行，还要配置 `~/.cargo/config`，反正比较麻烦，具体可以百度一下呢
msvc 安装方法简单，使用 vs 2019，安装完后，选择 `使用 c++ 的桌面开发`，这样就差不多了

能想到的就是这么多。

**Comment by crackfan** [comment]
> 我没有配什么环境变量，我这里的 Rust 环境都是新安装的，所以你就安装最新的版本就行了，不过我还是建议你使用 msvc 版本，因为 gnu 版本编译出来的二进制文件是 4 MB，而 msvc 版本编译出来就 1.5 MB。
> 
> gnu 版本要使用 msys2，安装后别忘记安装 cmake gcc base-devel mingw-w64-x86_64-toolchain 什么的，不安不行，还要配置 `~/.cargo/config`，反正比较麻烦，具体可以百度一下呢
> msvc 安装方法简单，使用 vs 2019，安装完后，选择 `使用 c++ 的桌面开发`，这样就差不多了
> 
> 能想到的就是这么多。



> 我没有配什么环境变量，我这里的 Rust 环境都是新安装的，所以你就安装最新的版本就行了，不过我还是建议你使用 msvc 版本，因为 gnu 版本编译出来的二进制文件是 4 MB，而 msvc 版本编译出来就 1.5 MB。
> 
> gnu 版本要使用 msys2，安装后别忘记安装 cmake gcc base-devel mingw-w64-x86_64-toolchain 什么的，不安不行，还要配置 `~/.cargo/config`，反正比较麻烦，具体可以百度一下呢
> msvc 安装方法简单，使用 vs 2019，安装完后，选择 `使用 c++ 的桌面开发`，这样就差不多了
> 
> 能想到的就是这么多。

vs2019 装了、见鬼啊~~流程都看似没问题的

**Comment by crackfan** [comment]
![image](https://user-images.githubusercontent.com/2922399/128604703-e76a5029-2fe1-4529-96d3-13b07b6a1f89.png)

**Comment by wtklbm** [comment]
MSVC 编译也报错吗？  贴出来看看

**Comment by crackfan** [comment]
![image](https://user-images.githubusercontent.com/2922399/128604883-c5db2063-d328-4391-83d3-04c4181b92c4.png)

**Comment by crackfan** [comment]
这里对吗？
![image](https://user-images.githubusercontent.com/2922399/128604950-f9ee3834-00ae-4ea4-a1c2-eb0a291bd180.png)

**Comment by wtklbm** [comment]
我没有用过 vs 自带的那个终端，我都是直接用 cmd 的哈

像这样
![2021-08-07_23 18 55](https://user-images.githubusercontent.com/26459487/128605081-e0e6a76b-0971-48ad-861e-840fbaaa926d.png)

**Comment by crackfan** [comment]
一模一样   搞了2 3天了 都这样见鬼
![image](https://user-images.githubusercontent.com/2922399/128605109-e40757e6-8905-4d62-8818-076b2e392a28.png)

**Comment by wtklbm** [comment]
安个别的试试，看看报错不：

```bash
cargo install cargo-edit cargo-watch cargo-audit onefetch rust-script
```

**Comment by wtklbm** [comment]
或者安装一下 `crm` 之前的老版本，比如 `0.0.3` `0.1.0` 这些，看看还有没有问题

**Comment by crackfan** [comment]
全新的系统没问题~~ 我现在用的系统不晓得哪里和rust冲突郁闷了

**Comment by wtklbm** [comment]
行，那如果 `crm` 使用过程中有问题，可以再联系我哈。

**Comment by crackfan** [comment]
非常好用~~

另外 alpine 的rust 各种异常问题 
换 用slim版本的 完全ok

![image](https://user-images.githubusercontent.com/2922399/128837491-9fc3debb-189c-40c8-8a8b-8a7ef84d26a4.png)
