### ISSUE TITLE
打印当前版本

### ISSUE THREAD

**Issue by TD-Sky** [wtklbm/crm#9]
请问crm有做这个功能吗？我在ArchLinux下尝试了

```shell
$ crm --version
$ crm -v
$ crm version
```
上述命令皆无效。

若crm没有此功能，可以加一个吗？

**Comment by wtklbm** [comment]
感谢您的建议，`crm` 目前已更新到 `v0.1.9`，并且增加了 `version` 和 `check-update` 命令。您可以切换到官方镜像源来安装最新版本。然后使用 `crm version` 来查看当前版本，并使用 `crm check-update` 来检测版本更新。
